//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesCompartidas
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Adelantos
    {
        public int Id { get; set; }
        public int Empleado { get; set; }
        public decimal Suma { get; set; }
        public int CantidadCuotas { get; set; }
        public bool Saldado { get; set; }
    
        public virtual Empleados Empleados { get; set; }
    }
}
