//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesCompartidas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuotas
    {
        public System.DateTime Vencimiento { get; set; }
        public int IdAdelanto { get; set; }
        public decimal Suma { get; set; }
        public bool Pagada { get; set; }
    }
}
