//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesCompartidas
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Entregas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entregas()
        {
            this.Paquetes = new HashSet<Paquetes>();
        }

        [Key]    
        public int Codigo { get; set; }
        public System.DateTime Fecha { get; set; }
        public string NombreReceptor { get; set; }
        public Nullable<long> ClienteReceptor { get; set; }
        public Nullable<long> ClienteEmisor { get; set; }
        public Nullable<int> LocalReceptor { get; set; }
        public Nullable<int> LocalEmisor { get; set; }
        public string Turno { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Clientes Clientes1 { get; set; }
        public virtual Locales Locales { get; set; }
        public virtual Locales Locales1 { get; set; }
        public virtual Turnos Turnos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paquetes> Paquetes { get; set; }
    }
}
