//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesCompartidas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paquetes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paquetes()
        {
            this.Reclamo = new HashSet<Reclamo>();
        }
    
        public int NumReferencia { get; set; }
        public System.DateTime FechaSalida { get; set; }
        public string Estado { get; set; }
        public string Ubicacion { get; set; }
        public Nullable<int> Entrega { get; set; }
        public Nullable<long> Cliente { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Entregas Entregas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reclamo> Reclamo { get; set; }
    }
}
