//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesCompartidas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registros
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal UtilidadBruta { get; set; }
        public decimal UtilidadOperacional { get; set; }
        public decimal UtilidadSinImpuestos { get; set; }
        public decimal UtilidadEjercicio { get; set; }
        public Nullable<int> BalanceId { get; set; }
    
        public virtual Balances Balances { get; set; }
    }
}
