//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesCompartidas
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Collections.Generic;
    
    public partial class Reparaciones
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public string Taller { get; set; }
        public decimal Monto { get; set; }
        public string Vehiculo { get; set; }
    
        public virtual Vehiculos Vehiculos { get; set; }
    }
}
