language: csharp
solution: "./EnviosService.sln"
script:
 - dotnet restore
install:
- travis_retry nuget restore -source "https://www.nuget.org/api/v2" ./EnviosService.sln
matrix:
  include:
    - dotnet: 1.1.5
      mono: none
      env: DOTNETCORE=1  # optional, can be used to take different code paths in your script
    - mono: latest