//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesCompartidas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnviosEntities : DbContext
    {
        public EnviosEntities()
            : base("EnviosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adelantos> Adelantos { get; set; }
        public virtual DbSet<Administradores> Administradores { get; set; }
        public virtual DbSet<Automobiles> Automobiles { get; set; }
        public virtual DbSet<Balances> Balances { get; set; }
        public virtual DbSet<Cadetes> Cadetes { get; set; }
        public virtual DbSet<Calificaciones> Calificaciones { get; set; }
        public virtual DbSet<Camiones> Camiones { get; set; }
        public virtual DbSet<Camionetas> Camionetas { get; set; }
        public virtual DbSet<Casillas> Casillas { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Cuotas> Cuotas { get; set; }
        public virtual DbSet<Empleados> Empleados { get; set; }
        public virtual DbSet<Entregas> Entregas { get; set; }
        public virtual DbSet<Galpones> Galpones { get; set; }
        public virtual DbSet<Gastos> Gastos { get; set; }
        public virtual DbSet<Impuestos> Impuestos { get; set; }
        public virtual DbSet<Ingresos> Ingresos { get; set; }
        public virtual DbSet<Locales> Locales { get; set; }
        public virtual DbSet<Motos> Motos { get; set; }
        public virtual DbSet<Multas> Multas { get; set; }
        public virtual DbSet<Palets> Palets { get; set; }
        public virtual DbSet<Paquetes> Paquetes { get; set; }
        public virtual DbSet<Racks> Racks { get; set; }
        public virtual DbSet<Reclamo> Reclamo { get; set; }
        public virtual DbSet<Registros> Registros { get; set; }
        public virtual DbSet<Reparaciones> Reparaciones { get; set; }
        public virtual DbSet<Sectores> Sectores { get; set; }
        public virtual DbSet<Turnos> Turnos { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Vehiculos> Vehiculos { get; set; }
    }
}
